version: 2.0
web_publish: &web_publish
  docker:
    - image: wilson208/circleci-awscli
  working_directory: ~/swayze-life
  steps:
    - checkout

    - run:
        name: Install Serverless CLI and dependencies
        command: |
            npm install

    - run:
        name: Setup Auth0 Key
        command: |
           echo "export const AUTH_CONFIG = { domain: '${AUTH0_DOMAIN}', clientId: '${AUTH0_CLIENT_ID}', callbackUrl: '${AUTH0_CALLBACK_URL}'}" > ~/swayze-life/src/Auth/auth0-variables.js

    - run:
        name: Publish to AWS
        command: |
            sls deploy --stage $SERVERLESS_RELEASE_CHANNEL
jobs:
  web_publish_to_aws_dev:
    environment:
      SERVERLESS_RELEASE_CHANNEL: dev
    <<: *web_publish

  web_publish_to_aws_prod:
    environment:
      SERVERLESS_RELEASE_CHANNEL: prod
    <<: *web_publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - web_publish_to_aws_dev:
          filters:
            branches:
              only: development

      - web_publish_to_aws_prod:
          filters:
            branches:
              only: release
