version: 2.0
web_publish: &web_publish
  docker:
    - image: wilson208/circleci-awscli
  working_directory: ~/swayze-life
  steps:
    - checkout

    - run:
        name: Install Serverless CLI and dependencies
        command: |
            npm install

    - run:
        name: Setup Auth0 Key
        command: |
           echo "export const AUTH_CONFIG = { domain: '${AUTH0_DOMAIN}', clientId: '${AUTH0_CLIENT_ID}', callbackUrl: '${AUTH0_CALLBACK_URL}'}" > ~/swayze-life/src/Auth/auth0-variables.js

    - run:
        name: Configure API
        command: |
          echo "export const config = { apiUrl: '${API_DOMAIN}'};" > ~/swayze-life/src/config.js

    - run:
        name: Build website
        command: |
            npm run build

    - run:
        name: Update Cloundfront if needed
        command: |
            sls deploy --stage $SERVERLESS_RELEASE_CHANNEL

    - run:
        name: Publish website
        command: |
            cd build
            aws s3 sync . s3://$SERVERLESS_S3_BUCKET
jobs:
  web_publish_to_aws_dev:
    environment:
      SERVERLESS_RELEASE_CHANNEL: dev
      SERVERLESS_S3_BUCKET: swayze-life-web-dev
      API_DOMAIN: https://klf0b851mc.execute-api.us-east-1.amazonaws.com/dev/
    <<: *web_publish

  web_publish_to_aws_prod:
    environment:
      SERVERLESS_RELEASE_CHANNEL: prod
      SERVERLESS_S3_BUCKET: swayze-life-web-prod
      API_DOMAIN: https://klf0b851mc.execute-api.us-east-1.amazonaws.com/prod/
    <<: *web_publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - web_publish_to_aws_dev:
          filters:
            branches:
              only: development

      - web_publish_to_aws_prod:
          filters:
            branches:
              only: release
